apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-backend
  labels:
    app: nginx
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
          tier: backend
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
